Repository 34th-SOPKATHON-iOS-TEAM1/iOS, pull requests merged in 2024-05, with the labels that each got.

#2 [Setting] 프로젝트 초기 세팅 (#1)
  .gitignore
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS.xcodeproj/project.pbxproj
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/AppDelegate.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/AccentColor.colorset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Extensions/UICollectionViewCell+.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Extensions/UIFont+.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Extensions/UIStackView+.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Extensions/UIView+.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Font/Pretendard-Black.otf
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Font/Pretendard-Bold.otf
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Font/Pretendard-ExtraBold.otf
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Font/Pretendard-ExtraLight.otf
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Font/Pretendard-Light.otf
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Font/Pretendard-Medium.otf
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Font/Pretendard-Regular.otf
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Font/Pretendard-SemiBold.otf
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Font/Pretendard-Thin.otf
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Info.plist
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/SceneDelegate.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/ViewController.swift
Labels: ⚙ Setting, 🍙 신영 🍙

#5 [Setting] #3 - Gray Color 에셋 추가
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/GrayColor/Black000.colorset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/GrayColor/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/GrayColor/Gray100.colorset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/GrayColor/Gray200.colorset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/GrayColor/Gray400.colorset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/GrayColor/Gray600.colorset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/GrayColor/Gray700.colorset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/GrayColor/Gray800.colorset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/GrayColor/White000.colorset/Contents.json
Labels: ⚙ Setting, 🍥 혜린 🍥

#6 [SETTING] 폰트 익스텐션 추가 (#4)
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS.xcodeproj/project.pbxproj
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Global/Extensions/UIFont+.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Global/Extensions/UILabel+.swift
Labels: ⚙ Setting, 🍎 희슬 🍎

#13 [FEAT] 스플래시 뷰 UI 구현 (#8)
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS.xcodeproj/project.pbxproj
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/OnBoarding/ViewControllers/OnBoardingViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/Splash/ViewControllers/SplashViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/SceneDelegate.swift
Labels: ✨ Feature, 🍎 희슬 🍎

#15 [Feature] #10 - 목표 등록 뷰 UI 구현 (TextField 제외)
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS.xcodeproj/project.pbxproj
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Global/Extensions/UIFont+.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Global/Extensions/UILabel+.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/RegisterToDoViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/View/RegisterNotToDoView.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/View/RegisterToDoView.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/ViewController/RegisterNotToDoViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/ViewController/RegisterToDoViewController.swift
Labels: ✨ Feature, 🍥 혜린 🍥

#18 [FEAT] 온보딩 뷰 구현 (#14)
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS.xcodeproj/project.pbxproj
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/PrimaryColor/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/PrimaryColor/mint100.colorset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/PrimaryColor/mint400.colorset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/SecondaryColor/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/SecondaryColor/brown100.colorset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/SecondaryColor/brown400.colorset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Global/Extensions/UIFont+.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Global/Resources/Font/Montserrat-Bold.otf
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Info.plist
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/OnBoarding/OnBoardingView.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/OnBoarding/ViewControllers/OnBoardingViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/OnBoarding/Views/OnBoardingView.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/SceneDelegate.swift
Labels: ✨ Feature, 🍎 희슬 🍎

#20 [Feat] ConfirmationAlert 구현 (#12)
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS.xcodeproj/project.pbxproj
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/seeSaw/cancel.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/seeSaw/cancel.imageset/cancel.png
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/Alert/AlertViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/ConfirmationAlert/ViewController/ConfirmationAlertViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/Success/SuccessViewController.swift
Labels: ✨ Feature, 🍙 신영 🍙

#25 [Feature] #16 - 목표 등록 뷰 UITextField 구현
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Global/Extensions/UILabel+.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/View/RegisterNotToDoView.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/View/RegisterToDoView.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/ViewController/RegisterNotToDoViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/ViewController/RegisterToDoViewController.swift
Labels: ✨ Feature, 🍥 혜린 🍥

#28 [FEAT] 온보딩 GUI 적용 (#19)
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/OnBoarding/ViewControllers/OnBoardingViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/OnBoarding/Views/OnBoardingView.swift
Labels: ✨ Feature, 🍎 희슬 🍎

#32 [Feat] #26 - 목표 등록 뷰 GUI 적용
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_brown_1.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_brown_1.imageset/Property 1=1_on.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_brown_2.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_brown_2.imageset/Property 1=2_on.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_brown_3.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_brown_3.imageset/Property 1=3_on.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_gray_1.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_gray_1.imageset/Property 1=1_off.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_gray_2.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_gray_2.imageset/Property 1=2_off.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_gray_3.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_gray_3.imageset/Property 1=3_off.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_mint_1.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_mint_1.imageset/Property 1=1_on-1.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_mint_2.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_mint_2.imageset/Property 1=2_on-1.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_mint_3.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_mint_3.imageset/Property 1=3_on-1.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/View/RegisterNotToDoView.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/View/RegisterToDoView.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/ViewController/RegisterNotToDoViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/ViewController/RegisterToDoViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/SceneDelegate.swift
Labels: ✨ Feature, 🍥 혜린 🍥

#39 [Refactor] #33 - clear button 추가 구현 및 화면 전환 구현
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/View/RegisterNotToDoView.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/View/RegisterToDoView.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/ViewController/RegisterNotToDoViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/ViewController/RegisterToDoViewController.swift
Labels: 🔨 Refactor, 🍥 혜린 🍥

#40 Feature/#38
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS.xcodeproj/project.pbxproj
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Network/RequestDTO/PostGoalRequestBody.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Network/RequestDTO/PostNotTodoRequestBody.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Network/RequestDTO/PostTodoRequestBody.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Network/ResponseDTO/BasicResponseDTO.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Network/ResponseDTO/GetAllResponseDTO.swift
Labels: ✨ Feature, 🍙 신영 🍙

#42 [FEAT] 모야 기본 세팅 (#37)
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Network/Base/BaseTargetType.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/SceneDelegate.swift
Labels: 📬 API, 🍎 희슬 🍎

#43 [Style] #41 - 에셋 수정 및 적용
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_brown_1.imageset/Property 1=1_on.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_brown_2.imageset/Property 1=2_on.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_brown_3.imageset/Property 1=3_on.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_gray_nega_1.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_gray_nega_1.imageset/img_gray_nega_1.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_gray_nega_2.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_gray_nega_2.imageset/img_gray_nega_2.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_gray_nega_3.imageset/Contents.json
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Assets.xcassets/Img/img_gray_nega_3.imageset/img_gray_nega_3.svg
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/View/RegisterNotToDoView.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/View/RegisterToDoView.swift
Labels: 🎨 Style, 🍥 혜린 🍥

#51 [FEAT] 서버통신 (#45)
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS.xcodeproj/project.pbxproj
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Info.plist
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Network/Base/BaseTargetType.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Network/OnBoarding/OnBoardingService.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Network/Register/RegisterService.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Network/ResponseDTO/BasicResponseDTO.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/ConfirmationAlert/ViewController/ConfirmationAlertViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/OnBoarding/ViewControllers/OnBoardingViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/OnBoarding/Views/OnBoardingView.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/ViewController/RegisterNotToDoViewController.swift
  34th-SOPKATHON-Team1-iOS/34th-SOPKATHON-Team1-iOS/Presentation/RegisterToDo/ViewController/RegisterToDoViewController.swift
Labels: 📬 API, 🍎 희슬 🍎
